version: '3'


services:
  es-client:
    image: es-client:0.1.1
    build:
      context: . # really only needs es.Dockerfile
      dockerfile: es.Dockerfile
  # image: name:tag
    ports:
    - "127.0.0.1:9200:9200"
    networks:
      default:
        ipv4_address: 172.19.0.3


  py-peline:
    image: py-peline:0.1.1
    build:
      context: . # needs app/ data/ and py.Dockerfile
      dockerfile: py.Dockerfile
  # image: name:tag
    ports:
      - "127.0.0.1:8888:8888"


# TODO: branch out notebook from pipeline
  # notebook:
  #   image: notebook:0.1.1
  #   build:
  #     context: . 
  #     dockerfile: jn.Dockerfile
  # # image: name:tag


networks:
  default:
    ipam:
      config:
        - subnet: 172.19.0.0/16