version: '3'


services:
  es-client:
    image: es-client:1.0 # call it vs1
    build:
      context: . # really only needs es.Dockerfile
      dockerfile: es.Dockerfile
    # container_name: elasticsearch
    ports:
      - "127.0.0.1:9200:9200" # runs on http://localhost:9200
    command: echo "ES run!"

  py-peline:
    image: py-peline:1.0 # call it vs1
    build:
      context: . # needs app/ data/ and py.Dockerfile
      dockerfile: py.Dockerfiler
    # command: python search.py
    command: echo "py-peline runs!"