version: '3'


services:
  es-client:
    image: es-client:0.1.1
    build:
      context: . # really only needs es.Dockerfile
      dockerfile: es.Dockerfile
    # container_name: elasticsearch
    ports:
      - "127.0.0.1:9200:9200" # runs on http://localhost:9200

  py-peline:
    image: py-peline:0.1.1
    build:
      context: . # needs app/ data/ and py.Dockerfile
      dockerfile: py.Dockerfile