version: '3'


services:
  es-client:
    image: es-client:0.1.1
    build:
      context: .
      dockerfile: es.Dockerfile
    ports:
    - "127.0.0.1:9200:9200"


  py-peline:
    image: py-peline:0.1.1
    build:
      context: . 
      dockerfile: py.Dockerfile
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - type: bind
        source: ./src/pipeline
        target: /app/src/pipeline



  gui-search:
    image: gui-search:0.1.1
    build:
      context: .
      dockerfile: fl.Dockerfile
    ports:
      - "127.0.0.1:5001:5001"
    volumes:
       - type: bind
         source: ./src
         target: /app/src
